#!/bin/bash

# Test Square Payment Script
# This script helps you create a test payment in Square Sandbox

echo "🧪 Square Payment Test Script"
echo "================================"
echo ""
echo "To process a test transaction, you need:"
echo "1. Your access token (from pos_integrations table)"
echo "2. Your location ID (store_id from pos_integrations table)"
echo ""
echo "📋 Step 1: Get your credentials from database"
echo "Run this SQL query in Supabase SQL Editor:"
echo ""
echo "SELECT merchant_id, store_id, access_token FROM pos_integrations WHERE provider = 'square' ORDER BY created_at DESC LIMIT 1;"
echo ""
echo "📋 Step 2: Once you have the access token and store_id, run:"
echo ""
echo "curl -X POST 'https://connect.squareupsandbox.com/v2/payments' \\"
echo "  -H 'Square-Version: 2024-12-03' \\"
echo "  -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"source_id\": \"cnon:card-nonce-ok\","
echo "    \"idempotency_key\": \"test-'$(date +%s)'\","
echo "    \"amount_money\": {"
echo "      \"amount\": 10000,"
echo "      \"currency\": \"USD\""
echo "    },"
echo "    \"location_id\": \"YOUR_LOCATION_ID\""
echo "  }'"
echo ""
echo "📋 Step 3: After creating the payment, check if webhook was received:"
echo ""
echo "SELECT * FROM webhook_logs WHERE provider = 'square' ORDER BY created_at DESC LIMIT 1;"
echo ""
echo "📋 Step 4: Check if transaction was created:"
echo ""
echo "SELECT * FROM pos_transactions WHERE pos_provider = 'square' ORDER BY created_at DESC LIMIT 1;"
echo ""
echo "================================"
echo "✅ If you see the transaction in the database, it worked!"
