// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etzwoyyhxvwpdejckpaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0endveXloeHZ3cGRlamNrcGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzAwMTIsImV4cCI6MjA3MzU0NjAxMn0.3RySB1tV2zIUjmRryWWwa18STlafjHBrxaKWwFAvKTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});